### ISSUE TITLE
2.CbhmC4F2.js:1882  Uncaught (in promise) ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by boxter007** [poloclub/transformer-explainer#9]
2.CbhmC4F2.js:1882  Uncaught (in promise) ReferenceError: caches is not defined
    at fetchModelChunks (2.CbhmC4F2.js:1882:34963)
    at fetchAndMergeChunks (2.CbhmC4F2.js:1882:35265)
    at 2.CbhmC4F2.js:1882:43228
    at J (scheduler.D_FMNFIv.js:1:270)
    at Array.map (<anonymous>)
    at index.BY8L5_Ir.js:4:2553
    at mt (scheduler.D_FMNFIv.js:1:9477)
    at Ct (index.BY8L5_Ir.js:4:3643)
    at new oe (app.BzvwbgBG.js:2:5236)
    at Xt (entry.Bes7zk-D.js:1:10885)

**Comment by aereeeee** [comment]
Hello @boxter007. Sorry for the late reply. 
It seems like the browser you're using might not support the caches API. Currently, we do not plan to support older browsers. You can check browser compatibility for the caches API here: https://developer.mozilla.org/en-US/docs/Web/API/Cache#browser_compatibility.
